New pull
GoetzDeBouville/Kotlin-Module-Project pull request #1
Opened 2023-03-21 09:09 UTC by GoetzDeBouville

2023-03-21 16:22 UTC, NoDopezzz requested changes

2023-03-21 16:22 UTC, NoDopezzz commented on src/main/kotlin/ArchiveSelectionScreen.kt
> +            if (choice == null || choice < 1 || choice > archives.size) {
⚠️ При неправильном вводе значения пользователю не предоставляется возможность повторить ввод и сразу "возвращает на предыдущий экран".

Кроме того, если ввести `choice = archives.size + 1` (кнопка "Назад"), то сработает первое условие и пользователю будет выведено сообщение _"Неверный выбор. Пожалуйста, попробуйте снова."_

<img width="582" alt="image" src="https://user-images.githubusercontent.com/56832972/226671660-3578dd8d-2dd1-4558-8bb4-de6ef27daab9.png">

2023-03-21 16:22 UTC, NoDopezzz commented on src/main/kotlin/NoteSelectionScreen.kt
> +    override fun show() {
⚠️ Экраны выбора - `ArchiveSelection` и `NoteSelection` имеют одинаковую логику и дублируют код друг друга.
Предлагаю вынести логику выбора в общий абстрактный класс, а классы наследники будут реализовывать список с пунктами и реакции на выбор

2023-03-21 22:37 UTC, GoetzDeBouville commented on src/main/kotlin/ArchiveSelectionScreen.kt
> +            if (choice == null || choice < 1 || choice > archives.size) {
Пофиксил

2023-03-22 15:32 UTC, NoDopezzz approved these changes

2023-05-20 16:45 UTC, merged